---
title: "Data Import"
output: github_document
---
```{r, echo = FALSE}
library (tidyverse)
library(readxl)
library(haven)
```

## Data Import: CSVs

Let's import data using the `readr` package

```{r}
litters_df = read_csv("data_import_examples/FAS_litters.csv")
litters_df = janitor::clean_names(litters_df)
```

look at the data
```{r}
litters_df
head(litters_df)
tail(litters_df)
```

```{r, eval= FALSE}
view(litters_df)
```

```{r}
skimr:: skim(litters_df)
```

`read_csv` options

## Other file formats

We need to read in an excel spreadsheet

```{r}
mlb_df = read_excel("data_import_examples/mlb11.xlsx")
```

```{r, eval = FALSE}
view(mlb_df)
```

```{r}
lotr_words_df = read_excel("data_import_examples/LotR_Words.xlsx",
range = "B3:D6")
```

## Still more formats

Read in a SAS dataset

```{r}
pulse_df =  read_sas("data_import_examples/public_pulse_data.sas7bdat")
```

```{r}
view(pulse_df)
```

## Data Export

```{r}
write_csv(lotr_words_df, file = "data_import_examples/lotr_words_df.csv")
```


